### ISSUE TITLE
Snapshot clusters by tag

### ISSUE THREAD

**Issue by davidloutsch** [awslabs/aurora-snapshot-tool#2]
Cloudformation does not currently support setting the cluster identifier. This makes snapshotting based on this name less useful. Would it be possible to snapshot based on a tag?

**Comment by mrcoronel** [comment]
Hi David, I'm closing this one out. It will take considerable work to implement. Since you are using Cloudformation to create your Aurora clusters, you'll be better off using a naming convention on your stack names and applying the filter on those. When Cloudformation creates Aurora clusters, it sets ClusterIdentifier to <stack-name>-random-id.
