### ISSUE TITLE
Can you go into detail about why this doesn't work with aurora-postgresql?

### ISSUE THREAD

**Issue by mgaut72** [awslabs/aurora-snapshot-tool#3]

**Comment by ahartma1** [comment]
I wondered this too and ultimately wrote my own function because this one didn't support deletion on multiple schedules (our org prunes the data at different intervals). But I believe it just needs a slight code change to include postgres, there should be no difference in the way snapshots are handled by the aws api the way i understand it. I haven't tested this but you could try it by changing line 42 in the snapshot_tool_utils.py to include a second value in the list.

_SUPPORTED_ENGINES = ['aurora', 'aurora-postresql']

**Comment by mgaut72** [comment]
@ahartma1 I had a successful experience by implementing your suggested change.  I'll close this issue, but suggest that awslabs go forward with this expansion of supported engines.
